/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sadoksync.sadoksync;

//import my.contacteditor.Client;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Arouz
 */
public class Lobby extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    Peer pr;
    ArrayList ali;

    /**
     * Creates new form panel
     */
    public Lobby(Peer pr) {
        this.pr = pr;
        this.ali = new ArrayList();
        initComponents();
        labelMyIP.setText("My Public IP: " + pr.myIP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldRegistryAddr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTdc = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Close = new javax.swing.JLabel();
        minimised = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelMyIP = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SADOK_LOGO_LOBBY.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 60));

        jList1.setBackground(new java.awt.Color(102, 102, 102));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 385, 230));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_start.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_start_pressed.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 502, 89, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-2_join_1.1.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-2_join.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, 385, 58));

        jTextFieldRegistryAddr.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldRegistryAddr.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRegistryAddr.setText("localhost");
        jTextFieldRegistryAddr.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRegistryAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistryAddrActionPerformed(evt);
            }
        });
        jTextFieldRegistryAddr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRegistryAddrKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldRegistryAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 122, 243, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registry: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_search.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_search_pressed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 85, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nick:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        jTextFieldNick.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldNick.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNick.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNickActionPerformed(evt);
            }
        });
        jTextFieldNick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNickKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 92, 243, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_set.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_set_pressed.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 85, -1));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 502, 200, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comunity Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 505, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 531, 385, 10));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direct Connect:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jTdc.setBackground(new java.awt.Color(102, 102, 102));
        jTdc.setForeground(new java.awt.Color(255, 255, 255));
        jTdc.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 537, 200, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_connect.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton5.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1_button_connect_pressed.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 536, 89, -1));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 3, 18, 18));

        minimised.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimised.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimisedMouseClicked(evt);
            }
        });
        getContentPane().add(minimised, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 3, 18, 18));

        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 90));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 10));

        labelMyIP.setForeground(new java.awt.Color(255, 255, 255));
        labelMyIP.setText("My Public IP:");
        getContentPane().add(labelMyIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        backGround.setForeground(new java.awt.Color(255, 255, 255));
        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1-Recovered.1.png"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cname = jTextField1.getText();
        if (!cname.equals("")) {
            ActionCreateComunity acc = new ActionCreateComunity(pr, jTextFieldRegistryAddr.getText(), cname, "Comunity Topic");
            //System.out.println("ActionCreateComunity: " + jTextFieldRegistryAddr.getText());
            jButton1.setEnabled(false);
            jTextField1.setEnabled(false);
            new Thread(acc).start();
        } else {
            //Complain
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldRegistryAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistryAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistryAddrActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!jTextFieldRegistryAddr.getText().isEmpty()) {
            ActionFindAllComunitys afac = new ActionFindAllComunitys(pr, jTextFieldRegistryAddr.getText());
            new Thread(afac).start();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int firstSelIx = jList1.getSelectedIndex();
        //String sel = (String) jList1.getModel().getElementAt(firstSelIx);
       String uuid = (String) ali.get(firstSelIx);
        ActionJoinComunitys afac = new ActionJoinComunitys(pr, jTextFieldRegistryAddr.getText(), uuid,false);
        new Thread(afac).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNickActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTextFieldNick.getText().length() > 2 && jTextFieldNick.getText().length() < 15) {
            ActionSetName asn = new ActionSetName(pr, jTextFieldNick.getText(), this);
            //jTextFieldNick.setEnabled(false);
            new Thread(asn).start();
            connectToDefaultSR();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldNickKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNickKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldNick.getText().length() > 2 && jTextFieldNick.getText().length() < 15) {
                ActionSetName asn = new ActionSetName(pr, jTextFieldNick.getText(), this);
                //jTextFieldNick.setEnabled(false);
                new Thread(asn).start();
                connectToDefaultSR();
            }
        }
    }//GEN-LAST:event_jTextFieldNickKeyPressed

    private void jTextFieldRegistryAddrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegistryAddrKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jTextFieldRegistryAddr.getText().isEmpty()) {
                ActionFindAllComunitys afac = new ActionFindAllComunitys(pr, jTextFieldRegistryAddr.getText());
                new Thread(afac).start();
            }
        }
    }//GEN-LAST:event_jTextFieldRegistryAddrKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String cname = jTextField1.getText();
            if (!cname.equals("")) {
                ActionCreateComunity acc = new ActionCreateComunity(pr, jTextFieldRegistryAddr.getText(), cname, "Comunity Topic");
                //System.out.println("ActionCreateComunity: " + jTextFieldRegistryAddr.getText());
                jButton1.setEnabled(false);
                jTextField1.setEnabled(false);
                new Thread(acc).start();
            } else {
                //Complain
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ActionDirectConnect adc = new ActionDirectConnect(pr, jTdc.getText());
        new Thread(adc).start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
       System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void minimisedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimisedMouseClicked
        this.setState(Lobby.ICONIFIED);
    }//GEN-LAST:event_minimisedMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
         xMouse = evt.getX();
         yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel frameDrag;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTdc;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldNick;
    private javax.swing.JTextField jTextFieldRegistryAddr;
    private javax.swing.JLabel labelMyIP;
    private javax.swing.JLabel minimised;
    // End of variables declaration//GEN-END:variables

    void clearList() {

         ali = new ArrayList();
        final DefaultListModel flm = new DefaultListModel();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jList1.setModel(flm);
            }
        });

    }
    private void connectToDefaultSR() {
        BufferedReader bufferedReader = null;
        try {
            bufferedReader = new BufferedReader(new InputStreamReader(new URL("http://sadoksync.site90.net/ip.html").openConnection().getInputStream()));

            
            final String fip = bufferedReader.readLine();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    jTextFieldRegistryAddr.setText(fip);
                }
            });

            ActionFindAllComunitys afac = new ActionFindAllComunitys(pr, fip);
            new Thread(afac).start();
        } catch (MalformedURLException ex) {
            Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bufferedReader.close();
            } catch (IOException ex) {
                Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
